# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [176]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [177]:
a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [178]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [179]:
a[2]

np.int64(300)

What are the values of index for series a?

In [180]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [181]:
a.index = ['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [182]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [183]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [184]:
b = pd.Series([800,450,100], index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [185]:
a = pd.concat([a,b])

In [186]:
#print a again after appending b into it

a = pd.concat([a,b])

Sort the values in descending order of a and print the index of the sorted series

In [187]:
a = a.sort_values(ascending=False)

In [188]:
print(a.index)

Index(['e', 'e', 'f', 'f', 'd', 'b', 'a', 'c', 'g', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [189]:
df = pd.DataFrame(a)

In [190]:
print(df)

     0
e  800
e  800
f  450
f  450
d  400
b  300
a  200
c  100
g  100
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [191]:
print(df.shape)

(10, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [192]:
# yep its same as the series.
df.index

Index(['e', 'e', 'f', 'f', 'd', 'b', 'a', 'c', 'g', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [193]:

df.head()

     0
e  800
e  800
f  450
f  450
d  400

In [194]:
df.tail()

     0
b  300
a  200
c  100
g  100
g  100

Rename the column of the dataframe as 'points'

In [195]:
df.columns = ['points']
print(df)

   points
e     800
e     800
f     450
f     450
d     400
b     300
a     200
c     100
g     100
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [196]:
#Create fruits array

fruits = np.random.choice(['orange','mango','apple'],7)

In [197]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits)

Change the index of fruits to the index of dataframe df

In [198]:
fruits_dict = dict(zip(df.index[:7], fruits.values))

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [199]:
df['fruits'] = df.index.map(fruits_dict)

In [200]:
print(len(df))
print(len(fruits))

10
7

In [201]:
print(df.head())
print("\nFull fruits column:")

   points fruits
e     800  mango
e     800  mango
f     450  apple
f     450  apple
d     400  mango

Full fruits column:

In [202]:
df.head()

   points fruits
e     800  mango
e     800  mango
f     450  apple
f     450  apple
d     400  mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [203]:
d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

Print(d1)

In [204]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [205]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [206]:
city = d1['city']

print city <br>
What is the type of city.

In [207]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [208]:
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})

print the shape of this dataframe

In [209]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [210]:
d3 = pd.concat([d1, d2], ignore_index=True)

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [211]:
cold_cities = d3[d3['Temperature'] <= 20]
print(cold_cities)
print(f"Number of cities with temp <= 20: {len(cold_cities)}")

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities with temp <= 20: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [212]:
hot_cities = d3[d3['Temperature'] >= 35]
print(hot_cities)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [213]:
# write function here

def is_ut(x):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return x in union_territories
    
#     # write code below
    
d3['is_ut'] = d3['city'].apply(is_ut)

In [214]:
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [215]:
# write function here
def c_to_f(celsius):
    return (celsius * 9/5) + 32

In [216]:
# check function c_to_f(10)
print(c_to_f(10))

50.0

In [217]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_fahrenheit'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  temp_fahrenheit
0   Chandigarh           15   True             59.0
1        Delhi           22   True             71.6
2       Kanpur           20  False             68.0
3      Chennai           26  False             78.8
4       Manali           -2  False             28.4
5    Bengalaru           24  False             75.2
6   Coimbatore           35  False             95.0
7    Srirangam           36  False             96.8
8  Pondicherry           39   True            102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [218]:

ut_cities_d1 = d1[d1['city'].apply(is_ut)]
print(ut_cities_d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [219]:
d3['temp_fahrenheit'] = d3['Temperature'].apply(c_to_f)
hot_f_cities = d3[d3['temp_fahrenheit'] > 90]
print(hot_f_cities)

          city  Temperature  is_ut  temp_fahrenheit
6   Coimbatore           35  False             95.0
7    Srirangam           36  False             96.8
8  Pondicherry           39   True            102.2

Select only the first three rows of the dataframe d1.

In [220]:
first_three = d1.head(3)
print(first_three)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [221]:
last_two_columns = d1.iloc[:, -2:]
print(last_two_columns)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [222]:
# Create a dataframe using dictionary of your choice

data = {
    'Department': ['HR', 'IT', 'IT', 'HR', 'Finance', 'Finance', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Salary': [50000, 75000, 80000, 55000, 90000, 85000, 70000],
    'Years': [5, 3, 4, 6, 8, 7, 2]
}
df_sample = pd.DataFrame(data)

In [223]:
# Use Groupby of single column with aggregate sum()
dept_salary_sum = df_sample.groupby('Department')['Salary'].sum()
print("Sum of salaries by department:\n", dept_salary_sum)

Sum of salaries by department:
 Department
Finance    175000
HR         105000
IT         225000
Name: Salary, dtype: int64

In [224]:
# Use Groupby of single column with aggregate count()
dept_count = df_sample.groupby('Department')['Employee'].count()
print("\nCount of employees by department:\n", dept_count)

Count of employees by department:
 Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [225]:
# Use Groupby of single column with aggregate min() and max()
dept_salary_min_max = df_sample.groupby('Department')['Salary'].agg(['min', 'max'])

In [226]:
print("\nMin and max salary by department:\n", dept_salary_min_max)

Min and max salary by department:
               min    max
Department
Finance     85000  90000
HR          50000  55000
IT          70000  80000

In [227]:
# Use Groupby of any 2 columns with aggregate mean()

dept_years_mean = df_sample.groupby(['Department', 'Years'])['Salary'].mean()
print("\nMean salary by department and years:\n", dept_years_mean)

Mean salary by department and years:
 Department  Years
Finance     7        85000.0
            8        90000.0
HR          5        50000.0
            6        55000.0
IT          2        70000.0
            3        75000.0
            4        80000.0
Name: Salary, dtype: float64

In [228]:
# Use Groupby of any 2 columns with aggregate min() and max()
dept_years_min_max = df_sample.groupby(['Department', 'Years'])['Salary'].agg(['min', 'max'])

In [229]:
print("\nMin and max salary by department and years:\n", dept_years_min_max)

Min and max salary by department and years:
                     min    max
Department Years
Finance    7      85000  85000
           8      90000  90000
HR         5      50000  50000
           6      55000  55000
IT         2      70000  70000
           3      75000  75000
           4      80000  80000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [230]:
a = pd.date_range(start='2020-01-01', end='2021-04-01', freq='D')

print a

In [231]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [232]:
print(f"Length of a: {len(a)}")

Length of a: 457

What is the type of a?

In [233]:
print(f"Type of a: {type(a)}")

Type of a: <class 'pandas.core.indexes.datetimes.DatetimeIndex'>